name: Close Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v2
      with:
        comment: "Hi and thanks for your interest in contributing. Unfortunately, we are no longer accepting Pull Requests on this project. Please check out the new [Lightning Web Components version of this app](https://github.com/dreamhouseapp/dreamhouse-lwc)."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}